// Generated by gencpp from file ucl_drone/FeaturesArrayRequest.msg
// DO NOT EDIT!


#ifndef UCL_DRONE_MESSAGE_FEATURESARRAYREQUEST_H
#define UCL_DRONE_MESSAGE_FEATURESARRAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucl_drone
{
template <class ContainerAllocator>
struct FeaturesArrayRequest_
{
  typedef FeaturesArrayRequest_<ContainerAllocator> Type;

  FeaturesArrayRequest_()
    {
    }
  FeaturesArrayRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FeaturesArrayRequest_

typedef ::ucl_drone::FeaturesArrayRequest_<std::allocator<void> > FeaturesArrayRequest;

typedef boost::shared_ptr< ::ucl_drone::FeaturesArrayRequest > FeaturesArrayRequestPtr;
typedef boost::shared_ptr< ::ucl_drone::FeaturesArrayRequest const> FeaturesArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ucl_drone

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ucl_drone': ['/home/felicien/Desktop/Devel-Tracking/shared-ros-workspace/src/ucl_drone/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ardrone_autonomy': ['/home/felicien/Desktop/UCL_drones/shared-ros-workspace/src/ardrone_autonomy/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucl_drone/FeaturesArrayRequest";
  }

  static const char* value(const ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FeaturesArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ucl_drone::FeaturesArrayRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UCL_DRONE_MESSAGE_FEATURESARRAYREQUEST_H
