// Generated by gencpp from file ucl_drone/MapChunk.msg
// DO NOT EDIT!


#ifndef UCL_DRONE_MESSAGE_MAPCHUNK_H
#define UCL_DRONE_MESSAGE_MAPCHUNK_H

#include <ros/service_traits.h>


#include <ucl_drone/MapChunkRequest.h>
#include <ucl_drone/MapChunkResponse.h>


namespace ucl_drone
{

struct MapChunk
{

typedef MapChunkRequest Request;
typedef MapChunkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapChunk
} // namespace ucl_drone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ucl_drone::MapChunk > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ucl_drone::MapChunk&) { return value(); }
};

template<>
struct DataType< ::ucl_drone::MapChunk > {
  static const char* value()
  {
    return "ucl_drone/MapChunk";
  }

  static const char* value(const ::ucl_drone::MapChunk&) { return value(); }
};


// service_traits::MD5Sum< ::ucl_drone::MapChunkRequest> should match 
// service_traits::MD5Sum< ::ucl_drone::MapChunk > 
template<>
struct MD5Sum< ::ucl_drone::MapChunkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ucl_drone::MapChunk >::value();
  }
  static const char* value(const ::ucl_drone::MapChunkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucl_drone::MapChunkRequest> should match 
// service_traits::DataType< ::ucl_drone::MapChunk > 
template<>
struct DataType< ::ucl_drone::MapChunkRequest>
{
  static const char* value()
  {
    return DataType< ::ucl_drone::MapChunk >::value();
  }
  static const char* value(const ::ucl_drone::MapChunkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ucl_drone::MapChunkResponse> should match 
// service_traits::MD5Sum< ::ucl_drone::MapChunk > 
template<>
struct MD5Sum< ::ucl_drone::MapChunkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ucl_drone::MapChunk >::value();
  }
  static const char* value(const ::ucl_drone::MapChunkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucl_drone::MapChunkResponse> should match 
// service_traits::DataType< ::ucl_drone::MapChunk > 
template<>
struct DataType< ::ucl_drone::MapChunkResponse>
{
  static const char* value()
  {
    return DataType< ::ucl_drone::MapChunk >::value();
  }
  static const char* value(const ::ucl_drone::MapChunkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UCL_DRONE_MESSAGE_MAPCHUNK_H
