// Generated by gencpp from file ucl_drone/SetPoseRef.msg
// DO NOT EDIT!


#ifndef UCL_DRONE_MESSAGE_SETPOSEREF_H
#define UCL_DRONE_MESSAGE_SETPOSEREF_H

#include <ros/service_traits.h>


#include <ucl_drone/SetPoseRefRequest.h>
#include <ucl_drone/SetPoseRefResponse.h>


namespace ucl_drone
{

struct SetPoseRef
{

typedef SetPoseRefRequest Request;
typedef SetPoseRefResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPoseRef
} // namespace ucl_drone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ucl_drone::SetPoseRef > {
  static const char* value()
  {
    return "259d6d91085aaefc76451f0ab02bff43";
  }

  static const char* value(const ::ucl_drone::SetPoseRef&) { return value(); }
};

template<>
struct DataType< ::ucl_drone::SetPoseRef > {
  static const char* value()
  {
    return "ucl_drone/SetPoseRef";
  }

  static const char* value(const ::ucl_drone::SetPoseRef&) { return value(); }
};


// service_traits::MD5Sum< ::ucl_drone::SetPoseRefRequest> should match 
// service_traits::MD5Sum< ::ucl_drone::SetPoseRef > 
template<>
struct MD5Sum< ::ucl_drone::SetPoseRefRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ucl_drone::SetPoseRef >::value();
  }
  static const char* value(const ::ucl_drone::SetPoseRefRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucl_drone::SetPoseRefRequest> should match 
// service_traits::DataType< ::ucl_drone::SetPoseRef > 
template<>
struct DataType< ::ucl_drone::SetPoseRefRequest>
{
  static const char* value()
  {
    return DataType< ::ucl_drone::SetPoseRef >::value();
  }
  static const char* value(const ::ucl_drone::SetPoseRefRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ucl_drone::SetPoseRefResponse> should match 
// service_traits::MD5Sum< ::ucl_drone::SetPoseRef > 
template<>
struct MD5Sum< ::ucl_drone::SetPoseRefResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ucl_drone::SetPoseRef >::value();
  }
  static const char* value(const ::ucl_drone::SetPoseRefResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucl_drone::SetPoseRefResponse> should match 
// service_traits::DataType< ::ucl_drone::SetPoseRef > 
template<>
struct DataType< ::ucl_drone::SetPoseRefResponse>
{
  static const char* value()
  {
    return DataType< ::ucl_drone::SetPoseRef >::value();
  }
  static const char* value(const ::ucl_drone::SetPoseRefResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UCL_DRONE_MESSAGE_SETPOSEREF_H
