// Generated by gencpp from file ucl_drone/SetPoseRefResponse.msg
// DO NOT EDIT!


#ifndef UCL_DRONE_MESSAGE_SETPOSEREFRESPONSE_H
#define UCL_DRONE_MESSAGE_SETPOSEREFRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucl_drone
{
template <class ContainerAllocator>
struct SetPoseRefResponse_
{
  typedef SetPoseRefResponse_<ContainerAllocator> Type;

  SetPoseRefResponse_()
    : status(false)  {
    }
  SetPoseRefResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetPoseRefResponse_

typedef ::ucl_drone::SetPoseRefResponse_<std::allocator<void> > SetPoseRefResponse;

typedef boost::shared_ptr< ::ucl_drone::SetPoseRefResponse > SetPoseRefResponsePtr;
typedef boost::shared_ptr< ::ucl_drone::SetPoseRefResponse const> SetPoseRefResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ucl_drone

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ucl_drone': ['/home/felicien/Desktop/Devel-Tracking/shared-ros-workspace/src/ucl_drone/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ardrone_autonomy': ['/home/felicien/Desktop/UCL_drones/shared-ros-workspace/src/ardrone_autonomy/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::ucl_drone::SetPoseRefResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucl_drone/SetPoseRefResponse";
  }

  static const char* value(const ::ucl_drone::SetPoseRefResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool status\n\
\n\
";
  }

  static const char* value(const ::ucl_drone::SetPoseRefResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetPoseRefResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucl_drone::SetPoseRefResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucl_drone::SetPoseRefResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCL_DRONE_MESSAGE_SETPOSEREFRESPONSE_H
