(cl:defpackage ucl_drone-srv
  (:use )
  (:export
   "SETPOSEREF"
   "<SETPOSEREF-REQUEST>"
   "SETPOSEREF-REQUEST"
   "<SETPOSEREF-RESPONSE>"
   "SETPOSEREF-RESPONSE"
   "MAPCHUNK"
   "<MAPCHUNK-REQUEST>"
   "MAPCHUNK-REQUEST"
   "<MAPCHUNK-RESPONSE>"
   "MAPCHUNK-RESPONSE"
   "FEATURESARRAY"
   "<FEATURESARRAY-REQUEST>"
   "FEATURESARRAY-REQUEST"
   "<FEATURESARRAY-RESPONSE>"
   "FEATURESARRAY-RESPONSE"
   "PROJECTION"
   "<PROJECTION-REQUEST>"
   "PROJECTION-REQUEST"
   "<PROJECTION-RESPONSE>"
   "PROJECTION-RESPONSE"
  ))

